name: 'metriql_data_studio_demo'
version: '1.0.0'
config-version: 2

profile: 'metriql_data_studio_demo'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  metriql_data_studio_demo:
      ecommerce:
          materialized: view
